module.exports=[
  [
    {
      "name":"setting",
      "src":"anchor://setting",
      "block":0,
      "base":true,
      "status":"normal",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"logo192.png",
      "short":"Setting",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://setting",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"logo192.png",
      "short":"Document",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://setting",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"logo192.png",
      "short":"Anchor",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://setting",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"logo192.png",
      "short":"Hello",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://setting",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"logo192.png",
      "short":"Gateway",
      "desc":""
    }
  ]
]