module.exports=[
  [
    {
      "name":"setting",
      "src":"anchor://setting",
      "block":0,
      "base":true,
      "status":"normal",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"icons/app_01.jpg",
      "short":"Setting",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://document",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"icons/app_02.jpg",
      "short":"Document",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://homepage",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"icons/app_03.jpg",
      "short":"Anchor",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://hello",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"icons/app_04.jpg",
      "short":"Hello",
      "desc":""
    },
    {
      "name":"setting",
      "src":"anchor://gateway_ui",
      "base":true,
      "status":"failed",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"icons/app_05.jpg",
      "short":"Gateway",
      "desc":""
    },
    {
      "name":"talking",
      "src":"anchor://freesaying",
      "base":true,
      "status":"installing",
      "type":"",
      "grid":{
        "size":[1,1],
        "position":[0,0],
      },
      "icon":"icons/app_06.jpg",
      "short":"talking",
      "desc":""
    }
  ]
]